### PR TITLE
add python3 support

### PR DESCRIPTION
**Pull request by Spectre5**
The README for this repository indicates that python3 should be used, but the code does not work in python3!  httplib doesn't exist in python3 as it has been replaced with http.client.  This pull request fixes this issue as well as a few changes for bytes vs strings in python3.  Lastly, it fixes a missing "f" for one of the f-strings.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Thank you! Merged!

**Comment by vadimkantorov** [comment]
I haven't really tested the code after trying to support python3, and it must have been in unworkable state. Thanks for fixing it!

**Comment by Spectre5** [comment]
Sure!  I only tested discovery and toggle and both of them work now.  I plan to test device reset and setup as that is something I'm particularly interested in.  Thanks for the code!

**Comment by vadimkantorov** [comment]
Exactly extreme bugginess / instability of Belkin bulbs / bridge and need for device reset/re-setups were why I lost interest to them :(

**Comment by Spectre5** [comment]
Yes, I would never buy them again!

**Pull request merged**
